# Generated by Django 4.2 on 2024-08-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='artist_images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_card', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('release_year', models.IntegerField()),
                ('picture', models.ImageField(upload_to='album_images')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.category')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.category'),
        ),
    ]
